repos:
  - repo: local
    hooks:
      - id: check-ansible-vault-encryption
        name: Check Ansible Vault Encryption
        entry: bash check_ansible_vault.sh
        language: system
        files: '^secrets\.yml$|.*/vars/.*\.yml$'
        stages: [commit]
