- name: Raspberry Pi 3 Model B config
  hosts: pi
  become: true
  vars_files:
    - vars/vault.yml
  tasks:      
    # - name: Tear down existing services
    #   community.docker.docker_compose_v2:
    #     project_src: srv/docker
    #     state: absent

    - name: Create Docker Compose file from Jinja template
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: srv/docker/docker-compose.yml
        mode: '0644'
      vars:
        - fr24key: "{{ secret_fr24key }}"
        - readsb_lat: "{{ secret_readsb_lat }}"
        - readsb_lon: "{{ secret_readsb_lon }}" 

    - name: Create and start services
      community.docker.docker_compose_v2:
        project_src: srv/docker
      register: output

    - name: Show results
      ansible.builtin.debug:
        var: output


  # roles:
  #   - geerlingguy.docker
  # pre_tasks: # runs before the roles
  #   - name: Perform a dist-upgrade.
  #     ansible.builtin.apt:
  #       upgrade: dist
  #       update_cache: yes

  #   - name: Check if a reboot is required.
  #     ansible.builtin.stat:
  #       path: /var/run/reboot-required
  #       get_checksum: no
  #     register: reboot_required_file

  #   - name: Reboot the server (if required).
  #     ansible.builtin.reboot:
  #     when: reboot_required_file.stat.exists == true

  #   - name: Remove dependencies that are no longer required.
  #     ansible.builtin.apt:
  #       autoremove: yes