- name: Raspberry Pi 3 Model B config
  hosts: pi
  become: true
  vars_files:
    - vars/secrets.yml
  tasks:
    - name: Tear down existing services
      community.docker.docker_compose_v2:
        project_src: /home/omadmin
        state: absent

    - name: Create Docker Compose file from Jinja template
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: docker-compose.yml
        mode: '0644'
      vars:
        fr24key: "{{ secret_fr24key }}"
        readsb_lat: "{{ secret_readsb_lat }}"
        readsb_lon: "{{ secret_readsb_lon }}"
        pihole_webpassword: "{{ secret_pihole_webpassword }}"

    - name: Create and start services
      community.docker.docker_compose_v2:
        project_src: /home/omadmin

    - name: Prune everything
      community.docker.docker_prune:
        containers: true
        images: true
        networks: true
        volumes: true
        builder_cache: true

    - name: Create and start services
      community.docker.docker_compose_v2:
        project_src: /home/omadmin

    - name: Get info on docker host
      community.docker.docker_host_info:

  # roles:
  #   - geerlingguy.docker
  pre_tasks: # runs before the roles
    - name: Perform a apt-get update
      ansible.builtin.apt:
        upgrade: "yes"
        update_cache: true

    - name: Check if a reboot is required.
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: false
      register: reboot_required_file

    - name: Reboot the server (if required).
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists

    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: true
