---
- name: Check if the Connected Machine Agent has already been downloaded on Windows servers
  win_stat:
    path: C:\Program Files\AzureConnectedMachineAgent
  register: azcmagent_win_downloaded
  when: ansible_os_family == 'Windows'

- name: Download the Connected Machine Agent on Windows servers
  win_get_url:
    url: https://aka.ms/AzureConnectedMachineAgent
    dest: C:\AzureConnectedMachineAgent.msi
  when: (ansible_os_family == 'Windows') and (not azcmagent_win_downloaded.stat.exists)

- name: Install the Connected Machine Agent on Windows servers
  win_package:
    path: C:\AzureConnectedMachineAgent.msi
  when: (ansible_os_family == 'Windows') and (not azcmagent_win_downloaded.stat.exists)

- name: Check if the Connected Machine Agent has already been connected on windows
  win_command: azcmagent check
  register: azcmagent_win_connected
  when: ansible_os_family == 'Windows'
  ignore_errors: true
  failed_when: (azcmagent_win_connected.rc not in [ 0, 16 ])
  changed_when: false

- name: Connect the Connected Machine Agent on Windows servers to Azure
  win_shell: |
    & $env:ProgramFiles\AzureConnectedMachineAgent\azcmagent.exe connect `
      --service-principal-id "{{ azure_arc_service_principal_id }}" `
      --service-principal-secret "{{ azure_arc_service_principal_secret }}" `
      --resource-group "{{ azure_arc_resource_group }}" `
      --tenant-id "{{ azure_arc_tenant_id }}" `
      --location "{{ azure_arc_location }}" `
      --subscription-id "{{ azure_arc_subscription_id }}"
  when: (ansible_os_family == 'Windows') and (azcmagent_win_connected.rc is defined and azcmagent_win_connected.rc != 0)
