plugin: community.proxmox.proxmox
# user: Environment variable: PROXMOX_USER
# url: Environment variable: PROXMOX_URL
validate_certs: false
want_facts: true
facts_prefix: proxmox_
group_prefix: proxmox_
want_proxmox_nodes_ansible_host: true
want_host_networks: true
keyed_groups:
  - key: proxmox_tags_parsed
    prefix: proxmox
    separator: "_"
compose:
  ansible_host: proxmox_agent_interfaces[0]['ip-addresses'][1].split('/')[0] if proxmox_agent_interfaces is defined
  ansible_user: "'Administrator'"
  ansible_connection: "'ssh'"
  ansible_shell_type: "'powershell'"
