plugin: community.proxmox.proxmox
# user: Environment variable: PROXMOX_USER
# url: Environment variable: PROXMOX_URL
validate_certs: false
want_facts: true
facts_prefix: proxmox_
group_prefix: proxmox_
want_proxmox_nodes_ansible_host: true
want_host_networks: true
keyed_groups:
  - key: proxmox_tags_parsed
    prefix: proxmox
    separator: "_"
compose:
  ansible_host: >-
    (proxmox_agent_interfaces[0]['ip-addresses'] | 
     map('regex_replace', '/.*', '') | 
     select('match', '^(?!127\.|169\.254\.|::1)[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$') | 
     first) if proxmox_agent_interfaces is defined and proxmox_agent_interfaces|length > 0 else ''
  ansible_user: "'Administrator'"
  ansible_connection: "'ssh'"
  ansible_shell_type: "'powershell'"
