---
- name: Configure Domain Controllers
  hosts: proxmox_windows_domain_controller
  vars_files:
    - vars/windows_lab_vars.yml
  roles:
    - windows_server_baseline
    - bginfo
    - domain_controllers
    - azure_arc

- name: Configure Windows Servers (Baseline only)
  hosts: proxmox_windows_server
  vars_files:
    - vars/windows_lab_vars.yml
  roles:
    - windows_server_baseline
    - bginfo
    - member_server

# Role specific configurations
- name: Configure Management Servers
  hosts: win-mgmt01
  vars_files:
    - vars/windows_lab_vars.yml
  roles:
    - windows_admin_center
    - azure_arc

# Configure Microsoft Entra Connect Server
- name: Configure Microsoft Entra Connect Server
  hosts: win-sync01
  vars_files:
    - vars/windows_lab_vars.yml
  roles:
    - microsoft_entra_connect_sync
    - azure_arc

# Configure Microsoft Entra Private Network Connector
- name: Configure Microsoft Entra Private Network Connector
  hosts: win-proxy01
  vars_files:
    - vars/windows_lab_vars.yml
  roles:
    - microsoft_entra_private_network_connector
    - azure_arc

# Configure Integration Runtime
- name: Configure Self-Hosted Integration Runtime
  hosts: win-ir01
  vars_files:
    - vars/windows_lab_vars.yml
  roles:
    - microsoft_integration_runtime
    - azure_arc
