---
- name: Hello Ansible
  ansible.builtin.debug:
    msg: "Hello Ansible, I am a {{ ansible_facts['windows_domain_role'] }} called {{ ansible_facts['hostname'] }} who's IP is {{ ansible_host }}"

- name: Set Local Administrator Password
  ansible.windows.win_user:
    name: Administrator
    password: "{{ local_admin_password }}"

- name: Set Timezone
  ansible.windows.win_timezone:
    timezone: New Zealand Standard Time
  register: result

- name: Set Hostname
  ansible.windows.win_hostname:
    name: "{{ inventory_hostname }}"
  register: result

- name: Reboot
  ansible.windows.win_reboot:
  when: result.reboot_required

- name: Enable ICMP
  community.windows.win_firewall_rule:
    name: ICMP Allow incoming V4 echo request
    enabled: true
    state: present
    profiles:
      - Domain
      - Private
      - Public
    action: allow
    direction: in
    protocol: icmpv4
    icmp_type_code:
      - '8:*'

- name: Change power plan to high performance
  community.windows.win_power_plan:
    name: high performance

- name: Disable Print Spooler Service
  ansible.windows.win_service:
    name: Spooler
    start_mode: disabled
    state: stopped

- name: Disable SMBv1
  ansible.windows.win_feature:
    name: FS-SMB1
    state: absent

- name: Stop Server Manager from starting at logon
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\ServerManager
    name: DoNotOpenServerManagerAtLogon
    data: 1
    type: dword

  # HideFirstRunExperience for Edge
- name: Hide First Run Experience for Edge
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Edge
    name: HideFirstRunExperience
    data: 1
    type: dword

- name: Disable IPv6 on Windows
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters
    name: DisabledComponents
    data: 0xff
    type: dword

- name: Configure Windows Update settings
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
    state: present
    data:
      - name: AUOptions
        type: dword
        data: 4
      - name: ScheduledInstallDay
        type: dword
        data: 0
      - name: ScheduledInstallTime
        type: dword
        data: 3
      - name: NoAutoUpdate
        type: dword
        data: 0
