---
- name: Copy proxy-conf sample files to new config and update DNS records
  hosts: unRAID
  vars:
    cloudflare_zone: malleynet.xyz
    services:
      - radarr
      - sonarr
      - frigate
      # Add more services here as needed
    remote_conf_path: /mnt/user/appdata/swag/nginx/proxy-confs
    local_conf_path: proxy-confs  # Path on localhost where custom confs are stored
  tasks:
    - name: Check if custom conf file exists
      ansible.builtin.stat:
        path: proxy-confs/{{ item }}.subdomain.conf
      register: stat_results
      delegate_to: localhost
      loop: "{{ services }}"

    - name: Copy custom conf file from localhost to remote server
      ansible.builtin.copy:
        src: "{{ local_conf_path }}/{{ item.item }}.subdomain.conf"
        dest: "{{ remote_conf_path }}/{{ item.item }}.subdomain.conf"
      when: item.stat.exists
      loop: "{{ stat_results.results }}"

    - name: Copy built-in sample conf
      ansible.builtin.copy:
        src: "{{ remote_conf_path }}/{{ item.item }}.subdomain.conf.sample"
        dest: "{{ remote_conf_path }}/{{ item.item }}.subdomain.conf"
        remote_src: true
      when: not item.stat.exists
      loop: "{{ stat_results.results }}"

    - name: Retrieve public IP address
      ansible.builtin.uri:
        url: http://api.ipify.org?format=json
        method: GET
        return_content: true
      register: ip_response
      delegate_to: localhost

    - name: Create a Cloudflare DNS record for each service
      community.general.cloudflare_dns:
        zone: "{{ cloudflare_zone }}"
        record: "{{ item }}.{{ cloudflare_zone }}"
        type: A
        value: "{{ ip_response.json.ip }}"
        proxied: true
      with_items: "{{ services }}"
      delegate_to: localhost
