trigger: none

schedules:
- cron: '0 0 * * *'
  displayName: Daily midnight build
  branches:
    include:
    - main

pool: pve-self-hosted-agents

variables:
  workingDirectory: $(System.DefaultWorkingDirectory)/workloads/rpi3b

steps:
- checkout: self
  displayName: 'Checkout repository'

- task: DownloadSecureFile@1
  name: ansibleSSHKey
  displayName: 'Download SSH private key'
  inputs:
    secureFile: 'ansible-rpi3b'

- script: |
    mkdir -p ~/.ssh
    cp $(ansibleSSHKey.secureFilePath) ~/.ssh/ansible-rpi3b
    chmod 600 ~/.ssh/ansible-rpi3b
  displayName: 'Setup SSH key'

- script: |
    ansible-galaxy install -r $(workingDirectory)/requirements.yml
  displayName: 'Install Galaxy Requirements'

- task: AzureCLI@2
  displayName: 'Run Ansible playbook'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
    workingDirectory: $(workingDirectory)
    visibleAzLogin: false
    azureSubscription: $(serviceConnection)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      ansible-playbook -i inventory.yml playbook.yml
  env:
    ANSIBLE_HOST_KEY_CHECKING: 'False'
    ANSIBLE_FORCE_COLOR: 'True'

- script: |
    rm -f ~/.ssh/ansible-rpi3b
  displayName: 'Cleanup SSH key'
  condition: always()